name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Prisma Client
        run: npx prisma generate
      
      - name: Push database schema
        run: npx prisma db push --accept-data-loss
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
      
      - name: Run TypeScript type check
        run: npm run type-check
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Run tests
        run: npm run test -- --testPathIgnorePatterns="tests/lib/redis.test.ts"
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          REDIS_URL: redis://localhost:6379
          APP_NAME: Test Store
          APP_URL: http://localhost:3000
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          REDIS_URL: redis://localhost:6379
          APP_NAME: Test Store
          APP_URL: http://localhost:3000
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: .next/
          retention-days: 7
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: quality-checks
    if: needs.quality-checks.result == 'success' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd /var/www/ea-commerce
            echo "🚀 Starting automated deployment..."
            git pull origin ${{ github.ref_name }}
            ./scripts/deploy.sh
            echo "✅ Deployment completed successfully!"

  build-status:
    runs-on: ubuntu-latest
    needs: [quality-checks, deploy]
    if: always()

    steps:
      - name: Check overall status
        run: |
          if [ "${{ needs.quality-checks.result }}" == "success" ] && [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "✅ All checks passed and deployment successful!"
            exit 0
          elif [ "${{ needs.quality-checks.result }}" == "success" ] && [ "${{ needs.deploy.result }}" == "skipped" ]; then
            echo "✅ Quality checks passed (deployment skipped for this branch)"
            exit 0
          else
            echo "❌ Pipeline failed - check quality checks or deployment"
            exit 1
          fi